### ISSUE TITLE
Play soperator in kind (CPU-only)

### ISSUE THREAD

**Issue by CrackedPoly** [nebius/soperator#153]
Hi people, I have tried and modified soperator in order to play it in kind with only CPU and **almost** everything goes fine. You can clone [this state](https://github.com/CrackedPoly/soperator/tree/07f604337eeb7b4026a0f6fe132873b1da3d8bb8) and have a try.

## ❗❗❗ See installation steps in my second comment to play

---

## Modification
I have modified some places to make it runnable:

### ‎helm/slurm-cluster/values.yaml
  - k8sNodeFilters to self-defined instead of nebius cloud's
  - storageClassName to `nfs` in kind instead of nebius cloud's
  - disable NCCL benchmark
  - lower resource requests (CPU, mem, volume)

### images/worker/slurmd_entrypoint.sh (this is runnable but something may be wrong)
I have modified the extraction of `CGROUP_PATH` in this script.

In kind,a slurmd is running in a pod (of a docker node). Thus, the content `/proc/self/cgroup` in slurmd's world should be something like `0::/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-pod252e517d_7722_424e_82d9_9514396935f1.slice/cri-containerd-9ab7d9f56928aece13edee1cb8e5ea1fb9ff0a8711f95b2debd0ab1bae8d487c.scope
`. So **theoretically** the `CGROUP_PATH` [here](https://github.com/CrackedPoly/soperator/commit/5eff95091e8d5a26220cdd38b2b20c954ce708d9#diff-9e90dcbf1100350ca32f5496062b222a6484fa33168142c891138e1d8619d4abR20) should be 4 levels in depth. When slurmd spawns a job, it should live in a cgroup under this level.

However, if we set this `CGROUP_PATH` to the 4-level path and create `system.slice` directory [there](https://github.com/CrackedPoly/soperator/blob/5eff95091e8d5a26220cdd38b2b20c954ce708d9/images/worker/slurmd_entrypoint.sh#L25), slurmd won't start correctly. This is because the cgroupv2 plugin of slurmd will only read 3 levels according to my tests (maybe their code don't expect this use case and see logs below), I have to set `CGROUP_PATH` to 3-level to make it work like normal.

(Below are the logs of slurmd starting if we set `CGROUP_PATH` to a 4-level path.)
```
cat /proc/self/cgroup
0::/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-pod252e517d_7722_424e_82d9_9514396935f1.slice/cri-containerd-9ab7d9f56928aece13edee1cb8e5ea1fb9ff0a8711f95b2debd0ab1bae8d487c.scope
cgroup v2 detected, creating cgroup for /kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-pod252e517d_7722_424e_82d9_9514396935f1.slice/cri-containerd-9ab7d9f56928aece13edee1cb8e5ea1fb9ff0a8711f95b2debd0ab1bae8d487c.scope
Link users from jail
Link home from jail because slurmd uses it
Bind-mount slurm configs from K8S config map
Make ulimits as big as possible
Apply sysctl limits from /etc/sysctl.conf
vm.max_map_count = 655300
Update linker cache
Complement jail rootfs
/mnt/jail /
Bind-mount virtual filesystems
Bind-mount cgroup filesystem
Remount /tmp
Bind-mount /var/log because it should be node-local
Bind-mount DNS configuration
Bind-mount /etc/hosts
Bind-mount jail submounts from upper /mnt/jail.upper into the actual /mnt/jail
Bind-mount enroot data directory because if should be node-local
Bind-mount slurm configs
Bind-mount slurmd spool directory from the host because it should be propagated to the jail
Update linker cache inside the jail
/
Waiting until munge is started
Skipping GPU detection
Start slurmd daemon
slurmd: debug:  Log file re-opened
slurmd: debug2: hwloc_topology_init
slurmd: debug2: xcpuinfo_hwloc_topo_load: xml file (/var/spool/slurmd/hwloc_topo_whole.xml) found
slurmd: debug:  CPUs:12 Boards:1 Sockets:1 CoresPerSocket:6 ThreadsPerCore:2
slurmd: debug3: Trying to load plugin /usr/lib/x86_64-linux-gnu/slurm/cgroup_v2.so
slurmd: debug3: plugin_load_from_file->_verify_syms: found Slurm plugin name:Cgroup v2 plugin type:cgroup/v2 version:0x180502
slurmd: error: common_file_write_content: unable to open '/sys/fs/cgroup/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-pod252e517d_7722_424e_82d9_9514396935f1.slice/system.slice/cgroup.subtree_control' for writing: No such file or directory
slurmd: error: Cannot enable cpuset in /sys/fs/cgroup/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-pod252e517d_7722_424e_82d9_9514396935f1.slice/system.slice/cgroup.subtree_control: No such file or directory
slurmd: error: common_file_write_content: unable to open '/sys/fs/cgroup/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-pod252e517d_7722_424e_82d9_9514396935f1.slice/system.slice/cgroup.subtree_control' for writing: No such file or directory
slurmd: error: Cannot enable memory in /sys/fs/cgroup/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-pod252e517d_7722_424e_82d9_9514396935f1.slice/system.slice/cgroup.subtree_control: No such file or directory
slurmd: error: common_file_write_content: unable to open '/sys/fs/cgroup/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-pod252e517d_7722_424e_82d9_9514396935f1.slice/system.slice/cgroup.subtree_control' for writing: No such file or directory
slurmd: error: Cannot enable cpu in /sys/fs/cgroup/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-pod252e517d_7722_424e_82d9_9514396935f1.slice/system.slice/cgroup.subtree_control: No such file or directory
slurmd: error: Could not create scope directory /sys/fs/cgroup/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-pod252e517d_7722_424e_82d9_9514396935f1.slice/system.slice/slurmstepd.scope: No such file or directory
slurmd: error: Couldn't load specified plugin name for cgroup/v2: Plugin init() callback failed
slurmd: error: cannot create cgroup context for cgroup/v2
slurmd: error: Unable to initialize cgroup plugin
slurmd: error: slurmd initialization failed
```

## Help Needed
Since I am not an expert in cgroup, so I can't tell whether the second point of the modification is wrong or not. IMHO, 4-level is the right one but slurmd only reads 3 levels, 3-level is wrong but it is currently the operational one.

Hope someone could investigate this to find out if it is a bug of slurmd or soperator.

**Comment by CrackedPoly** [comment]
# Get Started: Soperator in Kind

## Prerequisites

- Docker
- Kind
- Kubectl
- Helm

## Create a kind cluster

Create a kind cluster named mock-cluster with 3 worker nodes and 1 master node.

```sql
cat <<EOF | kind create cluster --name=mock-cluster --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: worker
- role: worker
- role: worker
- role: control-plane
  image: kindest/node:v1.31.0@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        "service-account-issuer": "kubernetes.default.svc"
        "service-account-signing-key-file": "/etc/kubernetes/pki/sa.key"
EOF
```

## Install nfs

```sql
helm repo add stable https://charts.helm.sh/stable

helm install nfs-server-provisioner stable/nfs-server-provisioner
```

## Install soperator

Clone [the repo](https://github.com/CrackedPoly/soperator/tree/07f604337eeb7b4026a0f6fe132873b1da3d8bb8) and checkout to `kind` branch.

```sql
git clone https://github.com/CrackedPoly/soperator.git && cd soperator

git checkout kind && cd helm

helm install soperator soperator
```

## Install slurm cluster

First, create necessary pv and pvc for the cluster.

```sql
kubectl apply -f manifest/controller-spool-pvc.yaml
kubectl apply -f manifest/jail-pvc.yaml
```

Before you install slurm cluster, find `sshRootPublicKeys` in helm/slurm-cluster/value.yaml and add a new public key to it. Later, you can only login to the slurm cluster with your corresponding private key.

Then, install the slurm cluster by helm. This process may take a long time, please wait for job `populate-jail` to complete and slurm pods to get up.

```sql
helm install slurm-cluster slurm-cluster
```

If everything goes fine, you will see the slurm login, controller and worker pods, which are spread to different nodes.

```sql
NAME                                                           READY   STATUS      RESTARTS   AGE     IP            NODE                   NOMINATED NODE   READINESS GATES
controller-0                                                   2/2     Running     0          3m41s   10.244.1.29   mock-cluster-worker2   <none>           <none>
controller-1                                                   2/2     Running     0          3m41s   10.244.2.25   mock-cluster-worker    <none>           <none>
login-0                                                        2/2     Running     0          3m41s   10.244.1.30   mock-cluster-worker2   <none>           <none>
login-1                                                        2/2     Running     0          3m41s   10.244.3.24   mock-cluster-worker3   <none>           <none>
nfs-server-provisioner-0                                       1/1     Running     0          18m     10.244.2.22   mock-cluster-worker    <none>           <none>
slurm1-populate-jail-xb8kc                                     0/1     Completed   0          4m11s   10.244.2.24   mock-cluster-worker    <none>           <none>
soperator-helm-soperator-controller-manager-5f5c69d54c-fkqzp   2/2     Running     0          15m     10.244.2.23   mock-cluster-worker    <none>           <none>
worker-0                                                       2/2     Running     0          3m41s   10.244.2.26   mock-cluster-worker    <none>           <none>
worker-1                                                       2/2     Running     0          3m41s   10.244.1.31   mock-cluster-worker2   <none>           <none>
worker-2                                                       2/2     Running     0          3m41s   10.244.3.25   mock-cluster-worker3   <none>           <none>
```

## Try the slurm cluster

After the installation, we can port-forward the login service to your host and access it.

```sql
kubectl port-forward services/slurm1-login-svc 2222:22

# In another terminal, run
ssh root@localhost -p 2222
```

### srun

Try your slurm cluster by srun:

```sql
# hostname are different in 3 jobs
srun -N 3 -n 3 --ntasks-per-node=1 hostname
 
# create a file in the login pod, the 3 jobs in other pods can also see it, 
# which means the jail works
touch hello_world
srun -N 3 -n 3 --ntasks-per-node=1 ls
```

### sbatch

Save this batch file to job.batch and run it by sbatch:

```sql
#!/bin/bash

#SBATCH -N 3
#SBATCH -n 3
#SBATCH --ntasks-per-node=1

hostname
```

```sql
root@login-0:~# sbatch job.sh
Submitted batch job 30
root@login-0:~# cat slurm-30.out
worker-2
worker-0
worker-1
slurmstepd: error: common_file_write_uints: write value '996' to '/sys/fs/cgroup/cgroup.procs' failed: Device or resource busy
slurmstepd: error: Unable to move pid 996 to init root cgroup /sys/fs/cgroup
```

This shows something is wrong...

**Comment by dstaroff** [comment]
Hi @CrackedPoly !
We really appreciate your contribution!

# helm/slurm-cluster/values.yaml

I basically agree with all your proposals in this section with a little exception:

`k8sNodeFilters` for custom nodes could also be commented out.

The reason is that some tools for infrastructure deployment (e.g. Terraform) do the merge strategy while deploying Helm releases. So, it could cause some collisions, that must be resolved by the practitioner. You may have to explicitly nullify default values in order to get a wanted result.

# slurmd_entrypoint.sh

Yeah. Our first approach with depth was to simply call mkdir for both levels. But we stopped at the current solution as it worked for us. I think we can re-play it again to also support kind.

# Kind

Did you try some other alternatives like minikube, MicroK8s, K3S, etc.?
We're curious if soperator could work in such environments and loads. However, running it in kind already sounds very promising.

Nicely done 🫡

---

BTW, you can take a look at [how we cook](https://github.com/nebius/nebius-solution-library/tree/main/soperator) soperator for Nebius Cloud via Terraform.

**Comment by Uburro** [comment]
https://github.com/nebius/soperator/pull/163 fixed

**Comment by Uburro** [comment]
@CrackedPoly Hi. This error occurs because Slurm in cgroup cannot find cpuset. In Kubernetes, for the cpuset cgroup to work, the pod must have a QoS of Guaranteed. [Kubernetes CPU Management Policies](https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#static-policy).

To solve your problem, you should configure the resources parameters on the worker nodes.
