### ISSUE TITLE
Multi-user cluster

### ISSUE THREAD

**Issue by thien-lm** [nebius/soperator#155]
I am wondering if i can set up multiple user to access the same slurm cluster?
As for now, i just see sshRootPublicKeys on slurm cluster configuration file, are there any options for other user to access slurm cluster ?

**Comment by rdjjke** [comment]
@thien-lm Many users can have access to the cluster. You just need to connect as root for the first time and create additional Linux users there (it's enough to create users on one Login node and they'll be available on all other nodes as the rootfs is shared).

There is a wrapper script `/usr/bin/createuser` that does the job: creates a user & group, populates the home directory, and saves an SSH key. Usage: `createuser bob --disabled-password`. But you can also create users using `adduser` or `useradd` utilities.

Soperator only manages SSH keys for the root user at the moment.

**Comment by thien-lm** [comment]
@rdjjke @Uburro 
Thanks for your help, i've found out the way to let multiple user to use the cluster.
