### ISSUE TITLE
sshd container failed to start: Directive 'MaxStartups' not allowed

### ISSUE THREAD

**Issue by george-kuanli-peng** [nebius/soperator#204]
Tag: `1.15.3`

In the login-0 pod, the sshd container failed to start with the following error message:

```
Start sshd daemon
/mnt/ssh-configs/sshd_config line 18: Directive 'MaxStartups' is not allowed within a Match block
```

The slurm1-ssh-configs configmap has these settings, generated by `internal/render/login/configmap.go`:

```
{
	"sshd_config": "LogLevel INFO
		Port 22
		PermitRootLogin yes
		PasswordAuthentication no
		ChallengeResponseAuthentication no
		UsePAM yes
		AcceptEnv LANG LC_*
		X11Forwarding no
		AllowTcpForwarding yes
		Subsystem sftp internal-sftp
		HostKey /etc/ssh/sshd_keys/ssh_host_rsa_key
		HostKey /etc/ssh/sshd_keys/ssh_host_ecdsa_key
		HostKey /etc/ssh/sshd_keys/ssh_host_ed25519_key
		Match User *
		    ChrootDirectory /mnt/jail
		ClientAliveInterval 9000
		ClientAliveCountMax 3
		MaxStartups 10:30:60
		LoginGraceTime9000
		MaxAuthTries4"
}
```

**Comment by george-kuanli-peng** [comment]
It is also noted that there are no spaces between `LoginGraceTime` and `9000`.

**Comment by Uburro** [comment]
HI.
This issue has already been [resolved]( https://github.com/nebius/soperator/pull/198). It will be included in the next release.

**Comment by george-kuanli-peng** [comment]
> HI. This issue has already been [resolved](https://github.com/nebius/soperator/pull/198). It will be included in the next release.

Thanks a lot!
