### ISSUE TITLE
Bug in deliver.sh for tests

### ISSUE THREAD

**Issue by rene-tech** [nebius/soperator#285]
The test/deliver.sh script is currently not working. 

```
ssh \
  -i "${KEY}" \
  -P "${PORT}" \
  "${USER}@${ADDRESS}" \

```

the port parameter should not be capital, that's only for scp. 

there are also some more issues with it. I can fix them if you can point me to the file, I don't find it in the repo?

**Comment by asteny** [comment]
It's in terraform solution repo https://github.com/nebius/nebius-solution-library/blob/main/soperator/test/deliver.sh
Please create new branch from release/soperator and create PR to it. Thanks!
